Add bookings
SvyatoslavLyskov/java-shareit pull request #6
Opened 2023-07-17 19:53 UTC by SvyatoslavLyskov

2023-07-18 17:44 UTC, Frilock requested changes
Добрый день, в целом мне работа понравилась и все в целом хорошо, но есть ряд предложений:
1. Полностью отсутствует логирование, предлагаю добавить его в слое сервиса, чтобы проще было дебажить/развивать приложение 
2. Просьба детализировать сообщение об ошибках, чтобы в них содержались какие то уникальные данные, позволяющие идентифицировать запрос
3. Лишние аннотации над интерфейсами
4. Правильным подходом считается, когда в класс вы инжектите интерфейсы, а не их реализации
5. В аннотации Column там где это возможно, нужно указывать размерность полей, которую вы задаете в скрипте
6. Другие комментарии по упрощению кода

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private final UserServiceImpl userService;
Правильнее инжектить интерфейс, а не реалиацию

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    @Transactional
У вас над классом стоит аннотация, значит если вы поведение не меняете, нет смысла ее ставить

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    @Transactional
Аналогично

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("У пользователя нет вещей.");
Нужно добавить детализации, чтобы было проще анализировать ошибку. Хотя бы идентификатор пользователя

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private void checkEnumExist(String state) {
Этот метод просится в сам енам

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemServiceImpl itemService;
Правильнее инжектить интерфейс

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getName() == null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +@Repository
Лишняя аннотация

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    List<ItemRequest> request;
Предложил бы сразу инициализировать коллекцию, дабы избежать лишних проверок на нул

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(name = "item_description", nullable = false)
В данной аннотации так же нужно указывать размерность полей, ту которую вы задаете в скрипте. Это нужно чтобы лишний раз не бегать в БД и уточнять, какого размера поле

2023-07-18 17:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +@Repository
Лишняя аннотация

2023-07-18 20:58 UTC, SvyatoslavLyskov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getName() == null) {
Я пытался уже,раньше так и было,почему-то у меня валятся тесты постмана)Что-то делаю не так,наверное)

2023-07-19 09:18 UTC, Frilock approved these changes
Добрый день, работа принята, но в части логирования, я бы посоветовал логировать не весь обьект, а только код или идентификатор, иначе это будет не читабельно

2023-07-19 09:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        log.info("Добавлено бронирование {}", booking);
Полностью логгировать обьект тоже не очень идея, он может быть большой и вы простыню увидите в логе. Логируйте, например, ид или код или что то такое

2023-07-19 11:16 UTC, merged